[book]
authors = ["Posthuman Studios", "Luiz Borges Gomide", "Xeno"]
language = "en"
multilingual = false
src = "src"
title = "Eclipse Phase Compilations and Homebrew"
description = "Addition Eclipse Phase resources used in my own games."

[build]
build-dir = "docs/"
create-missing = false

[output.html]
additional-css = ["ep2e.css"]
no-section-label = false
git-repository-url = "https://github.com/XenoMath/EP2e-Resources/tree/main/src"
site-url = "/ep/"

[output.html.print]
enable = false

[output.html.fold]
enable = true

[output.html.search]
enable = true
use-boolean-and = true
